# hotel-service.yml in GitHub repo
server:
  port: 8082

spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_management
    username: root
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
   # config:
   #   import: "optional:aws-parameterstore:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  resource:
    attributes:
      service:
        name: hotel-service
  traces:
    sampler:
      ratio: 1.0
# In hotel-service's application.yml
logging:
  level:
    io.awspring.cloud: DEBUG
    org.springframework.cloud: DEBUG
